replicaCount: 3

image:
  repository: "https://us-central1-docker.pkg.dev/prime-freedom-418105/artemis/artemis"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"


  service: 
  type: ClusterIP
  port: 5000

